# site settings
title: My
subtitle: Portfolio
email: heynbron@gmail.com
description: Passionate Educator and Lifelong Learner
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 7911 Flower St  
city: Arvada
state: CO
zip_code: 80005
country: United States of America
phone: (720) 569-5052

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/nicole-hb
  GitLab:
  Google-Plus:
  Instagram: https://www.instagram.com/param.somewhere/
  LinkedIn: https://www.linkedin.com/in/nicole-heyn-brontis
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
